### PR TITLE
Miscellaneous changes to prepare for submission

### PR DESCRIPTION
**Pull request by jjc2718**
Changes:
* Fixed some small formatting issues in author metadata
* Add line break suggested by @dhimmel for readability (in #12)
* Add annotation formatting required by journal (the asterisks in citations break GitHub's Markdown syntax highlighting but look fine in the HTML/PDF paper after running the build, not sure why the mismatch)
* Add acknowledgements section (@cgreene: do we need to list funding sources here too?)

Still TODO:
* Graphical abstract
* I'd like to make a figure comparing hand-engineered sequence features to CNNs (as suggested by @dhimmel). I don't think this should be too hard.
* Would be nice to add a table(s) describing input/output for models, but as this counts toward word count we're unlikely to have space

### CODE REVIEW

**Comment by dhimmel** [comment]
> Add annotation formatting required by journal

Can you elaborate what these asterisks are for? Perhaps there is a better solution.

> the asterisks in citations break GitHub's Markdown syntax highlighting but look fine in the HTML/PDF paper after running the build, not sure why the mismatch

They are different markdown parsers that both implement things beyond the commonmark standard.

**Comment by jjc2718** [comment]
> Can you elaborate what these asterisks are for? Perhaps there is a better solution.

From the journal's Guide for Authors: "At least 10% of (the references) should be selected and annotated as being papers of special interest (•) or outstanding interest (••)"

You can see the annotations in an article here: https://www.sciencedirect.com/science/article/pii/S0958166919300643 (see, for instance, reference 3)

I tried escaping the asterisks inside of the reference square brackets, but then they don't show up at all.

**Comment by dhimmel** [comment]
From https://www.elsevier.com/journals/current-opinion-in-biotechnology/0958-1669/guide-for-authors I see:

> The majority of the references (please aim to cite approximately 50) should come from the period under review (i.e. the past two years) and, in general, at least 10% of these should be selected and annotated as being papers of special interest (•) or outstanding interest (••). Annotated references MUST be from the past two years, and the annotation should provide a brief description of the major findings and the importance of the study. This is an essential part of each review and is very popular with our readers. For example:
> • 30. Wong FS, Karttunen J, Dumont C, Wen L, Visintin I, Pilip IM, Shastri N, Pamer EG, Janeway CA Jr: Identification of an MHC class I-restricted autoantigen in type 1 diabetes by screening an organ-specific cDNA library. Nat Med 1999, 5:1026-1031.
> Using class I tetramers, the authors demonstrate that insulin-specific CD8+ T cells account for a large proportion of infiltrated T cells in the islets of prediabetic NOD mice. This is the first study to use peptide multimers to decipher the mechanism of autoimmunity.

It doesn't make much sense to manually prefix citations, when actually you're applying this label on a per-reference basis. For example, currently you could accidentally apply asterisks to one citation but not the other for the same work.

Would it make the most sense to just add the asterisks in your reference annotation document? It seems like in the author guidelines, they want the special/outstanding interest denoted in the references (and then in their system they create the in-text asterisks). Just my reading, could be wrong.

**Comment by jjc2718** [comment]
@dhimmel that makes sense, I'll remove the inline asterisks and just keep them in the reference annotations for now.

**Comment by cgreene** [comment]
@jjc2718 - with the funding info in the header, hopefully it'll be fine for now.

**Pull request merged**
